POST http://199.241.138.64/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAyNjUyODkzLCJleHAiOjE2MDI2NTM3OTN9.ywxBRThAfXvwzUoRQuYAJGNS5OmCH9rJXXQrFlayUdE

{
    
}

###
PATCH   http://199.241.138.64/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAyMzYxMjc0LCJleHAiOjE2MDIzNjIxNzR9.nSFhG5vgLhKGQrBICi2I8LHhgz5wLa7FbSLFd2wpFrY
Content-Type: application/json

{
    "firstname" : "brando"
}

###

POST http://199.241.138.64/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAxODc1OTMyLCJleHAiOjE2MDE4NzU5NjJ9.Rc0WDJvyFyEmjGbHzRTaFWHuYi2-F0nqOp94F26Cq5Q"
}

###


###
POST  http://199.241.138.64/users/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "123123123"
}


###

DELETE  http://199.241.138.64/users/logout
Content-Type: application/json


{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAxODc0NTg4LCJleHAiOjE2MDE4NzU0ODh9.AWM2NDWywraDZ_V-RIiTViSv_y1grq5nBaDrfzhJ1_s"
}


###
GET http://199.241.138.64/agents/6/vessel/
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAyMzgzMDUwLCJleHAiOjE2MDIzODM5NTB9.rkCxsHwkSB2YATIgGCHn3N6Ppts9_7YOkKkmb2vtfFk

# {
#      "shipping_agent_name":"agent asdadadad",
#      "e_add":"rafael@update.com"

# }

###

POST   http://199.241.138.64/vessels/
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAyNDk0MTYwLCJleHAiOjE2MDI0OTUwNjB9.1LX9ZYqTUgcwdcjUjcpir9EepaRTFYVtNx8VxS4yvsA
 
{
   "vessel_name":"try",
      "vessel_flag":2,
      "imonumber":"imo",
      "GRT":2,
      "DWT":3,
      "NRT":4,
      "LOA":5,
      "breadth":"wew",
      "callsign":"wewewew",
      "shipping_agent_id":8

}


###

PATCH   http://199.241.138.64/crews/4  
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAyNTE3NjM1LCJleHAiOjE2MDI1MTg1MzV9.ys7_sayILVTkDyxMNPC97RAeUSEjUtYHUG8c3_ZGjY8


{
    "firstname": "asdasd",
"fullname": "asdasd dasdad",
"id": 4,
"is_fil": 1,
"lastname": "dasdad",
"middlename": "asda",
"status": "0",
"vessels_id": 12
}


###

POST  http://199.241.138.64/bookings/vessel
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAyNTI3NDEyLCJleHAiOjE2MDI1MjgzMTJ9.LimtBfNUm04HULtTgQGdJCMhz-E9VTcZzkb8hwcd1k0

{
      "shipping_id": 8
}
###

GET  http://localhost:5000/arrivals/
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAzNTI4ODE0LCJleHAiOjE2MDM1Mjk3MTR9.ngJy7s3hsHY5PzfWXXvhSqQN1MxerRDLAOP2s4kFbdg

# {
#     "date": "2020-10-14"
# }

###

POST http://199.241.138.64/departure/vessel
Content-Type:  application/json

{
      "shipping_id": 6
}

###
POST  http://localhost:5000/basicinfo
Content-Type:  application/json

{
     "shipping_license_no" : "asdas",
    "contact_person" : "asdad",
    "cno": "asdad",
    "quaratine_facility": "asdad",
    "quaratine_address": "asdadassdasdadasdasdada",
    "quaratine_cno": "asda",
    "callsign": "dasd",
    "shipping_agency_name": "adad",
    "crew_service_boat": "asda",
    "vehicle_type": "dasdas",
    "vehicle_model": "asdas",
    "vehicle_plate_no": "asd",
    "driver_name": "asd",
    "driver_cno": "asdasdasdasda"
}

###


GET http://199.241.138.64/vesselinfo/basic/16
Content-Type:  application/json

#  {
   
#     "vessel_name": "asda",
#     "flag_registry": "dasda",
#     "voyage_no": "dasda",
#     "grt": 124,
#     "nrt": 123,
#     "dwt": 123,
#     "loa": 123,
#     "breadth": 1231123,
#     "name_last_port": "asdad",
#     "departure_last_port": "asda",
#     "basic_info_id": 3
#   }


### 

GET http://localhost:5000/newcrew/basic/16
Content-Type:  application/json


##

GET http://199.241.138.64/basicinfo/16
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjAzNjY5MjAzLCJleHAiOjE2MDM2NzAxMDN9.VBKUmPkFoS5KztMQ3LCO8C2t2Z1oOlFiu6uhPj8pS_I
#  {
#    "name_master": "sdadasasdsdadas",
#     "no_fil_crews": 2,
#     "no_for_crews": 2,
#     "no_fil_singin": 2,
#     "no_for_singin": 2,
#     "no_fil_singoff": 2,
#     "no_for_signoff": 2,
#     "names_fil_singin": "asdadasdad",
#     "names_for_singin": "adadadasdad",
#     "names_fil_singoff": "asdsadad",
#     "names_for_singoff": "sadadadadsadsa",
#     "basic_info_id": 3
#   }

###
GET http://localhost:5000/arrivals/basic/16
Content-Type:  application/json

# {
   
#    "draft": "asdad",
#     "berth": "adsasdasd",
#     "date": "2020-10-24",
#     "time": "09:06:00",
#     "purpose": "asdadad",
#     "discharged": 400,
#     "loaded": 400,
#     "basic_info_id": 3
# }

###

GET http://199.241.138.64/departure/basic/16
Content-Type:  application/json

# {
#    "date": "2020-10-24",
#     "time": "08:00:00",
#     "portcall": "asdas",
#     "basic_info_id": 3
# }


###

GET http://199.241.138.64/bookings
Content-Type:  application/json

{
   "date": "2020-10-24",
    "time": "09:00:00",
    "basic_info_id": 3
}


